### ISSUE TITLE
회고 상세 조회 기능 생성

### ISSUE THREAD

**Issue by rlawltjd8547** [f-lab-edu/subsclife-be#22]
# 이슈

> 생성할 이슈에 대한 내용을 작성해주세요.

회고 목록및 상세 조회 기능 생성하기

<br>

## 할 일

> 할 일을 작성해주세요.

- [x] 회고 상세조회 기능 

<br>

## 참고 사항

> 참고 사항이 있다면 첨부해주세요.

<br>

**Comment by hyeok-kong** [comment]
`상세 조회` 시 다른 사용자의 회고 또한 반환해야 합니다
