### ISSUE TITLE
로그인 (사용자 데이터 반환) 기능

### ISSUE THREAD

**Issue by rlawltjd8547** [f-lab-edu/subsclife-be#3]
# 이슈

> 생성할 이슈에 대한 내용을 작성해주세요.
- 로그인 기능의 필요한 것들을 구현합니다

<br>

## 할 일

> 할 일을 작성해주세요.

- [ ] 엔티티 클래스 작성
- [ ] 구현부 생성

<br>

## 참고 사항

> 구현부 생성시 컨벤션 참고하여 구현 하기, 확장성있게끔 항상 생각할것  

<br>

**Comment by hyeok-kong** [comment]
코드 컨벤션 및 스타일 파악을 위해 `페어 프로그래밍` 으로 진행할 예정입니다.
